GET http://localhost:3000/users

###


POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "fullname": "Amazing Person",
    "password": "password"
}

###

POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMTYwNzMxNWI1NWRmM2Q3YzYxNTQ2ZiIsImlhdCI6MTY0NTYyNTk4NiwiZXhwIjoxNjQ1NzEyMzg2fQ.xJcS_s4GDklVDyAIKU0tjWm7JY8nvsl7gBgkBxlDyW4


{
    "title": "hoodie",
    "category": "tops",
    "price": 2,
    "description": "A hoodie",
    "img": "alskdfj;al"
}

###